server.port=8181
file.server-path=uploads/
file.client-path=/images/**

app.seed.admin.email=admin@example.com
app.seed.admin.password=admin123
app.seed.admin.first-name=System
app.seed.admin.last-name=Admin
app.seed.admin.role=ADMIN
